### ISSUE TITLE
Integrate with pipeline templates from vscode-engineering

### ISSUE THREAD

**Issue by deepak1556** [microsoft/zeromq-prebuilt#26]
As part of aligning core extensions that rely on native modules to have similar glibc constraints as core, I will be adding template steps that configures the C++ toolchain in the [vscode-engineering repo](https://github.com/microsoft/vscode-engineering/issues/456).

In its current state this repo will not be able to benefit from the above change, one idea discussed with @joaomoreno was to use the upstream zeromq.js project directly in the jupyter extension so that module files get built as expected. But I now realized this is a no go, although the patch changes are minimal the blocker would be upstream zeromq already publishes prebuilds and we cannot override them to force rebuild in the jupyter extension.

So now coming to the other alternative, the vscode-engineering repo also contains templates for building and publishing npm packages https://github.com/microsoft/vscode-engineering/wiki/NPM-Packages-Build-and-Publish. I will also add the compiler configuration to those templates as well. I see that the npm package https://github.com/microsoft/vscode-zeromq currently downloads the prebuilts from this repo github releases and replaces them for the prebuilds from the upstream zeromq project during postinstall step in the jupyter extension project. I suggest the following path instead,

1) Merge `microsoft/zeromq-prebuilt` and `microsoft/vscode-zeromq` into a single npm package that builds, publishes the vscode specific prebuilds to npm
2) The combined repo uses the npm pipeline templates from the vscode-engineering repo
3) Jupyter extension will depend on this new npm package that will still replace the prebuilds from upstream zeromq as part of postinstall step.

Only difference between now and the proposed solution, prebuilds are published to npm rather than github releases and sharing the pipeline templates allows to get the glibc compatibility free of cost.

What are you thoughts on this @DonJayamanne and let me know if you have alternate ideas.

**Comment by joaomoreno** [comment]
Does npm allow publishing platform specific packages?

**Comment by deepak1556** [comment]
Not that I know of https://github.com/npm/rfcs/discussions/120, packages have been publishing prebuilds into a single npm and pick the right one via helper libraries like https://github.com/prebuild/prebuildify?tab=readme-ov-file#prebuildify
