### ISSUE TITLE
macOS binaries do not build with node 20

### ISSUE THREAD

**Issue by rzhao271** [microsoft/zeromq-prebuilt#34]
I tried bumping the CI to use node 20.x (i.e. 20.18.0) and 20.17.x and both bumps seemed to break the macOS builds.
Even though the build step is green in both cases, the "List zeromq.js files" step reveals that ./prebuilds/darwin-x64 does not have any binaries generated under it, indicating that the build is not actually valid.

node 20.18.0 https://dev.azure.com/monacotools/Monaco/_build/results?buildId=299737&view=results (I believe the Publish Symbols failure is unrelated)
node 20.17.0 https://dev.azure.com/monacotools/Monaco/_build/results?buildId=301686&view=results

**Comment by deepak1556** [comment]
Addressed in 085adb17ba219fa12eca1cc1e6b64259a87372ed

Note: most of our zeromq.js patches will go away if we update to the latest stable release of v6 from upstream, should be a follow-up.
